### ISSUE TITLE
tried to use it on raspberry pi 4 and is not working 

### ISSUE THREAD

**Issue by fmuntean** [MichaIng/nodejs-linux-installer#3]
the list did not return anything for armv71

**Comment by MichaIng** [comment]
You mean then trying to list unofficial builds? That is expected since ARMv7 is fully supported by official builds, so there are no unofficial builds (required) for this architecture. Here is the full list of unofficial builds, as you can see it contains only special architectures or those where official support has been dropped for (x86-32, ARMv6): https://unofficial-builds.nodejs.org/download/release/index.tab

**Comment by fmuntean** [comment]
I was trying to use this script to install the nodejs v16 LTS on the raspberry pi 4.

**Comment by MichaIng** [comment]
Ah, so far it does not support selecting a specific version from official builds, but would be actually nice to have. To switch to v16 you could currently do:
```sh
sudo npm i -g n
sudo n 16
```

**Comment by MichaIng** [comment]
I added now an option to install specific Node versions as well for official builds. All available versions can now be listed with:
```sh
./node-install.sh --list
```
And a specific version installed with:
```sh
sudo ./node-install.sh --version v16.20.2
```
